# Generated by Django 3.1.7 on 2021-04-05 09:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Add_New_Category', models.CharField(max_length=20)),
                ('Category_vehicle_img', models.ImageField(default='', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Add_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Add_New_Company', models.CharField(max_length=20)),
                ('Add_Company_Logo', models.ImageField(default='', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_name', models.CharField(max_length=50)),
                ('Seat_capacity', models.IntegerField(default=1)),
                ('Fuel_type', models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('electric', 'Electric')], default='petrol', max_length=20)),
                ('Gear_type', models.CharField(choices=[('manual', 'manual'), ('automatic', 'automatic')], default='manual', max_length=20)),
                ('Year_of_mfg', models.IntegerField(default=2000)),
                ('Rent_cost', models.IntegerField()),
                ('Front_img', models.ImageField(upload_to='images')),
                ('Side_img', models.ImageField(upload_to='images')),
                ('Rear_img', models.ImageField(upload_to='images')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('End_date', models.DateField(default=datetime.date(2021, 5, 5))),
                ('status', models.BooleanField(default=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideon.add_categories')),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideon.location')),
                ('Company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideon.add_company')),
            ],
        ),
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('pickd', models.DateField()),
                ('pickt', models.TimeField()),
                ('pickl', models.CharField(max_length=10)),
                ('dropd', models.DateField()),
                ('dropt', models.TimeField()),
                ('dropl', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=False, verbose_name='Accept')),
                ('carid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideon.vehicles')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
